######################################################################
# Automatically generated by qmake (1.07a) Mon Jan 28 04:57:38 2008
######################################################################

TEMPLATE = app
DEPENDPATH += src
INCLUDEPATH += . src

# Input
HEADERS += src/launcher.h
SOURCES += src/launcher.cpp src/main.cpp

qt+= gui
